### ISSUE TITLE
accessing predicted values, variance/std for training and testing data

### ISSUE THREAD

**Issue by FanwangM** [oaoni/sklearnBPMF#2]
Thank you for building this wrapper and it makes things easier.  I am also very interested in `smurff` and I would like to access

- [x] average values of training data
- [X] average values of testing data
- [x] variance/std of predictions on training data
- [X] variance/std of predictions on testing data

The marked part has been implemented in your wrapper, can you tell me how can I access others? Thank you. @oaoni

**Comment by oaoni** [comment]
Hey, with the latest commit, I've added support for predicting average values and standard deviations on the training set.

**Comment by FanwangM** [comment]
Hi! Thank you for implementing this.
I am going to close this issue.
